Исправлено: AttributeError: type object 'Memory' has no attribute 'get_data' TypeError: learn() missing 1 required positional argument: 'data'